name: frontend
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  grpc: ^3.0.0
  flutter_login: ^2.0.0-nullsafety.0
  bottom_navy_bar : ^6.0.0
  fluttertoast: ^8.0.6
  email_validator: ^2.0.1
  qr_code_scanner: ^0.7.0
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  sqflite: ^2.0.2
  auto_size_text: ^3.0.0
  connectivity_plus: ^2.2.1
  go_router: ^3.0.5
  card_swiper: ^2.0.3
  uuid: ^3.0.6
  device_info_plus: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/banner/
    - assets/images/button/
    - assets/images/slider/

  fonts:
    - family: FZFYSJW
      fonts:
        - asset: assets/fonts/FZFYSJW.ttf

    - family: Vladimir
      fonts:
        - asset: assets/fonts/Vladimir.ttf

    - family: NSSC
      fonts:
        - asset: assets/fonts/NSSC.otf

flutter_native_splash:
  background_image: "assets/images/splash.png"
  web: false
  fullscreen: true
