name: frontend
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  grpc: ^3.0.0
  provider: ^6.0.2
  flutter_login: ^3.2.0
  bottom_navy_bar : ^6.0.0
  fluttertoast: ^8.0.6
  email_validator: ^2.0.1
  qr_code_scanner: ^0.7.0
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
#  sqflite: ^2.0.2
  auto_size_text: ^3.0.0
#  connectivity_plus: ^2.2.1
  go_router: ^3.0.5
  card_swiper: ^2.0.3
  uuid: ^3.0.6
  device_info_plus: ^3.2.2
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.0
  flutter_staggered_grid_view: ^0.6.1
  material_design_icons_flutter: 5.0.6595
  line_awesome_flutter: ^2.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.1
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/banner/
    - assets/images/button/
    - assets/images/slider/

  fonts:
    - family: FZFYSJW
      fonts:
        - asset: assets/fonts/FZFYSJW.ttf

    - family: FZFYKSJZ
      fonts:
        - asset: assets/fonts/FZFYKSJZ.ttf

    - family: Vladimir
      fonts:
        - asset: assets/fonts/Vladimir.ttf

    - family: NSSC
      fonts:
        - asset: assets/fonts/NSSC.otf

    - family: KaiTi
      fonts:
        - asset: assets/fonts/KaiTi.ttf

flutter_native_splash:
  background_image: "assets/images/splash.png"
  web: false
  fullscreen: true
