version: '1'
services:
  museum:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  redis:
    image: "redis:latest"
    restart: always
