// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: service/proto/auth.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthError int32

const (
	AuthError_MISMATCHED_PASSWORD AuthError = 0
	AuthError_NONEXISTENT_USER    AuthError = 1
	AuthError_DUPLICATED_NAME     AuthError = 2
	AuthError_UNKNOWN             AuthError = 3
)

// Enum value maps for AuthError.
var (
	AuthError_name = map[int32]string{
		0: "MISMATCHED_PASSWORD",
		1: "NONEXISTENT_USER",
		2: "DUPLICATED_NAME",
		3: "UNKNOWN",
	}
	AuthError_value = map[string]int32{
		"MISMATCHED_PASSWORD": 0,
		"NONEXISTENT_USER":    1,
		"DUPLICATED_NAME":     2,
		"UNKNOWN":             3,
	}
)

func (x AuthError) Enum() *AuthError {
	p := new(AuthError)
	*p = x
	return p
}

func (x AuthError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthError) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_auth_proto_enumTypes[0].Descriptor()
}

func (AuthError) Type() protoreflect.EnumType {
	return &file_service_proto_auth_proto_enumTypes[0]
}

func (x AuthError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthError.Descriptor instead.
func (AuthError) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_auth_proto_rawDescGZIP(), []int{0}
}

type AuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   *AuthError `protobuf:"varint,2,opt,name=error,proto3,enum=z.museum.auth.AuthError,oneof" json:"error,omitempty"`
}

func (x *AuthReply) Reset() {
	*x = AuthReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReply) ProtoMessage() {}

func (x *AuthReply) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReply.ProtoReflect.Descriptor instead.
func (*AuthReply) Descriptor() ([]byte, []int) {
	return file_service_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthReply) GetError() AuthError {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return AuthError_MISMATCHED_PASSWORD
}

var File_service_proto_auth_proto protoreflect.FileDescriptor

var file_service_proto_auth_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x7a, 0x2e, 0x6d, 0x75,
	0x73, 0x65, 0x75, 0x6d, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x22, 0x3d, 0x0a, 0x0b, 0x41, 0x75, 0x74,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x64, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x33, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18,
	0x2e, 0x7a, 0x2e, 0x6d, 0x75, 0x73, 0x65, 0x75, 0x6d, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x41,
	0x75, 0x74, 0x68, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2a, 0x5c,
	0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x17, 0x0a, 0x13, 0x4d,
	0x49, 0x53, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x45, 0x44, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f,
	0x52, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x4e, 0x4f, 0x4e, 0x45, 0x58, 0x49, 0x53, 0x54,
	0x45, 0x4e, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x44, 0x55,
	0x50, 0x4c, 0x49, 0x43, 0x41, 0x54, 0x45, 0x44, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x02, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x03, 0x32, 0x95, 0x01, 0x0a,
	0x0c, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x41, 0x0a,
	0x07, 0x4f, 0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x2e, 0x7a, 0x2e, 0x6d, 0x75, 0x73,
	0x65, 0x75, 0x6d, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x7a, 0x2e, 0x6d, 0x75, 0x73, 0x65, 0x75, 0x6d, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x42, 0x0a, 0x08, 0x4f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x12, 0x1a, 0x2e, 0x7a,
	0x2e, 0x6d, 0x75, 0x73, 0x65, 0x75, 0x6d, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x41, 0x75, 0x74,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x7a, 0x2e, 0x6d, 0x75, 0x73,
	0x65, 0x75, 0x6d, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x54, 0x45, 0x4e, 0x58, 0x2d, 0x53, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_proto_auth_proto_rawDescOnce sync.Once
	file_service_proto_auth_proto_rawDescData = file_service_proto_auth_proto_rawDesc
)

func file_service_proto_auth_proto_rawDescGZIP() []byte {
	file_service_proto_auth_proto_rawDescOnce.Do(func() {
		file_service_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_proto_auth_proto_rawDescData)
	})
	return file_service_proto_auth_proto_rawDescData
}

var file_service_proto_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_proto_auth_proto_goTypes = []interface{}{
	(AuthError)(0),      // 0: z.museum.auth.AuthError
	(*AuthRequest)(nil), // 1: z.museum.auth.AuthRequest
	(*AuthReply)(nil),   // 2: z.museum.auth.AuthReply
}
var file_service_proto_auth_proto_depIdxs = []int32{
	0, // 0: z.museum.auth.AuthReply.error:type_name -> z.museum.auth.AuthError
	1, // 1: z.museum.auth.Authenticate.OnLogin:input_type -> z.museum.auth.AuthRequest
	1, // 2: z.museum.auth.Authenticate.OnSignUp:input_type -> z.museum.auth.AuthRequest
	2, // 3: z.museum.auth.Authenticate.OnLogin:output_type -> z.museum.auth.AuthReply
	2, // 4: z.museum.auth.Authenticate.OnSignUp:output_type -> z.museum.auth.AuthReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_proto_auth_proto_init() }
func file_service_proto_auth_proto_init() {
	if File_service_proto_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_proto_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_service_proto_auth_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_proto_auth_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_auth_proto_goTypes,
		DependencyIndexes: file_service_proto_auth_proto_depIdxs,
		EnumInfos:         file_service_proto_auth_proto_enumTypes,
		MessageInfos:      file_service_proto_auth_proto_msgTypes,
	}.Build()
	File_service_proto_auth_proto = out.File
	file_service_proto_auth_proto_rawDesc = nil
	file_service_proto_auth_proto_goTypes = nil
	file_service_proto_auth_proto_depIdxs = nil
}
